### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pwyq** [WarshipGirls/WGViewer#2]
- [ ] 新功能
	- [x] 自动打决战E6
		- [x] 设置自动兑换战备券
	- [ ] 一键每日5次摸头
	- [ ] 自动配装
	- [ ] 航海记录
		- [ ] 建造出货（公式，旗舰）
		- [ ] 开发出货
		- [ ] 战斗记录（掉落，mvp）没有出货，就没有历史记录
		- [x] 每小时油弹钢
		- [x] 每日油弹钢分布
	- [ ] 允许道中玩家接管战斗
	- [ ] 允许人工出击
	- [x] countdowns
		- [x] 中国北京时区，本地时区
		- [x] 每日/每周/倒计时
		- [x] all countdown (docking/constructing/developing/expedition/tasks) on one place
		- [x] 限时任务
	- [ ] 可以自定义建造，开发公式
		- [ ] 每日刷新出任务时，自动建造/开发
	- [ ] 战斗记录
		- [ ] 记录战斗全过程（包括A打了B多少血，B打了A多少血）
	- [ ] E6-1 A 低费船练级
	- [ ] Side dock displays 签名 + editing
	- [ ] multi-language support
	- [x] display 决战 磁带数量
	- [ ] dynamic updates remaining task time
		- avg_time x remaining amount = total time
		- avg_time = completed time / completed amount
	- [x] Multi-layer encrypt
		- [x] encrypt with username/uid
- [ ] 优化
	- [x] 面板显示 总（装备/技能加成）
	- [ ] 装备不足，尝试从其他舰娘身上拆下
	- [ ] 单个舰娘的装备一键清空
	- [ ] 自动任务时开启每日10次战役支援
	- [ ] 练级任务时吃饭
	- [x] 远征设置无缝衔接转换
	- [ ] 强化指定特定狗粮（而不是舰种）
	- [x] 点击exe的时候自动登录
	- [ ] 每日任务刷新时，app也刷新
	- [ ] 今日出征资源变动
		- [ ] 合并/展开 相同任务
	- [ ] 演习刷新掉报社队，争取轻母队
	- [ ] text box长度 部分船只技能描述过长
	- [ ] Repairs all damaged ships with one button (and queueing)
	- [ ] Sort self-defined auto task name alphabetically
	- [ ] When a ship is on the Rank, blacklist it and change a ship (instead of stop entire sortieing)
	- [ ] Dock
		- [ ] 勾选，一键unlock（而不是一个个拆）
		- [ ] 分解指定5，6星装备
	- [ ] 一键离队
	- [ ] same line up for different sortie maps
	- [ ] lineup slot limits > 36
	- [ ] lineup select-all or multi-selection (drag-select); not click one by one
- [x] UI/UX
	- [x] 暗系背景UI
	- [x] 全屏
	- [x] 英文界面
	- [x] 全船坞单独窗口
		- [x] 浏览船坞时候不会因为任务自动跳转
- [x] Just TODO
	- [x] https://stackoverflow.com/questions/6932389/how-to-remotely-update-python-applications
	- [x] pyinstaller not working

**Comment by pwyq** [comment]
kantaiRT stupidly reset all my linup settings. one more reason and motive to write my own tool

**Comment by pwyq** [comment]
- [ ] same line up for different sortie maps

**Comment by pwyq** [comment]
- [ ] lineup slot limits > 36

**Comment by pwyq** [comment]
- [ ] lineup select-all or multi-selection; not click one by one
